name: Deploy Eleventy to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Specify your Node.js version
          cache: "npm"

      - name: Install dependencies
        run: npm ci # Use 'npm install' if you don't have a package-lock.json

      - name: Build with Eleventy
        run: npx @11ty/eleventy # Or your custom build command

      # If you have a custom domain, uncomment the next step and create a CNAME file
      # - name: Create CNAME file
      #   run: echo "www.yourdomain.com" > _site/CNAME # Replace with your custom domain

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
